### ISSUE TITLE
Problem writing to excel sheet

### ISSUE THREAD

**Issue by edstead** [Abdelrahman-Hekal/Google_Maps_Scraper#1]
Hi there, ive been trying to use this code. Im having an issue writing to excel file, they are all coming up blank. 

The only kind of error im reading is:

Scraping the info for result 1/12
The below error occurred while scraping: "Query"
'DataFrame' object has no attribute 'append'

Any idea why this is happening for me?

**Comment by Abdelrahman-Hekal** [comment]
Hi,
Looks like you are using v2 of the Pandas library that doesn't support the attribute 'append' for the dataframes, I have pushed an update that supports V2.0 as well that should work with you.
